name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run:  uname -a 
      - name: second  step
        run: ls
      - name: Thhird step
        run: date
